name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build to dist
      run: cd $GITHUB_WORKSPACE/building && ./build.sh
      
    - uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUBTOKEN }}
        expire-in: 0

    - name: Store artifacts
      uses: actions/upload-artifact@v2
      with:
        name: arma3life
        path: dist/*
